In [2]:
import numpy as np

In [3]:
h = [2,1,0]
x = [3, 4, 5]
y = np.convolve(x,h)
y

array([ 6, 11, 14,  5,  0])

In [4]:
import numpy as np
x = [6,2]
h = [1,2,5,4]
y = np.convolve(x, h, 'full')

In [5]:
y

array([ 6, 14, 34, 34,  8])

In [6]:
x = [6,2]
h = [1,2,5,4]

In [7]:
y = np.convolve(x,h, 'same')

In [8]:
y

array([ 6, 14, 34, 34])

In [9]:
y = np.convolve(x, h, 'valid')

In [10]:
y

array([14, 34, 34])