In [2]:
import tensorflow as tf

In [3]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
a = tf.constant([2], name = 'constant_a')
b = tf.constant([3], name = 'constant_b')

2023-07-24 12:47:30.625262: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2023-07-24 12:47:30.625317: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2023-07-24 12:47:30.625333: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2023-07-24 12:47:30.625828: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-07-24 12:47:30.626151: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [5]:
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

In [6]:
tf.print(a.numpy()[0])

2


In [7]:
@tf.function
def add (a,b):
    c = tf.add(a,b)
    print(c)
    return c

In [12]:
result = add(a,b)
result.numpy()

array([5], dtype=int32)

Different datatypes

In [14]:
scalar = tf.constant(2)
vector = tf.constant([5,6,2])
matrix = tf.constant([[1,2,3],[2,3,4], [3,4,5]])
tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])

In [15]:
scalar.shape

TensorShape([])

In [16]:
tensor.shape

TensorShape([3, 3, 3])

In [18]:
tf.debugging.set_log_device_placement(True)

m1 = tf.constant([[2,3], [3,4]])
m2 = tf.constant([[2,3], [3,4]])

@tf.function
def mathmul():
    return tf.matmul(m1,m2)

mul_op = mathmul()
print(mul_op)

tf.Tensor(
[[13 18]
 [18 25]], shape=(2, 2), dtype=int32)


2023-07-24 12:58:38.117842: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


In [19]:
v = tf.Variable(0)

In [20]:
@tf.function
def incrementByOne(v):
    v = tf.add(v,1)
    return v

In [21]:
for i in range(3):
    v = incrementByOne(v)
    print(v)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


2023-07-24 13:20:34.894728: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-07-24 13:20:34.902680: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
